---

##- hosts: homeservers
#- hosts: all
- hosts: all
  become: true
  tasks:

  - name: install updates on my home servers (Ubuntu & Debian)
    apt:
      upgrade: dist
      update_cache: yes
##    when: ansible_distribution == "Ubuntu"
