---
- name: Upgrade Packages and Notify
  hosts: all
#  gather_facts: true
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
   #     autoremove: yes
   #    autoclean: yes

    - name: Check reboot file
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Send email notification via SMTP
      community.general.mail:
        host: "{{ smtp_server }}"
        port: 465
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: Tony Krajcik <tony@linuxdoma.sk>
        subject: Ansible-report
        body: Server {{ ansible_hostname }} vyzaduje restart systému .
      delegate_to: localhost
      when: reboot_required.stat.exists
      