---

- name: Server Updates and Restart Notification
  hosts: all
  gather_facts: true

  tasks:
    - name: Check for available updates
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      register: apt_update

    - name: Check if restart is required
      shell: needs-restarting -r
      register: needs_restart
      changed_when: false
      ignore_errors: true
      when: apt_update.changed

    - name: Install updates
      apt:
        upgrade: dist
        update_cache: yes
      register: apt_upgrade
      when: apt_update.changed

    - name: Send restart notification
      mail:
        host: smtp.wy.sk
        port: 465
        username: watchtower@no-wire.sk
        password: Watchtower2021
        to: vawaver@gmail.com
        subject: "Alert: Server requires restart"
        body: Please restart the server as updates have been installed.
      when: needs_restart.stdout != "0" and apt_upgrade|changed

